### ISSUE TITLE
Aesthetic/Design Updates 2-12-2020

### ISSUE THREAD

**Issue by devinHST** [stuartlynn/NYCCensusCountMap#13]
- [x] Place search bar either below the blurb about the map within that box, or in the upper right-hand corner above the scale bar and zoom buttons.
_If placed in NE corner, place in this order: Search bar, scale bar, zoom buttons._
- [x] Make the font size for everything in the information box proportionately larger. Maybe by 2-4pts
- [x] Make the pie charts a bit larger.
- [x] Change "Metric" to "Neighborhood Information"
- [ ] Add some space between the drop down for "Boundaries" and the title "Community Assets"
- [x] Add some space between "Community Assets" title and "Educational Assets"

**Comment by stuartlynn** [comment]
These should be done now. Deploying shortly to the live site
